import PyInstaller.__main__
import sys
import os

# 切换到脚本所在目录
os.chdir(os.path.dirname(os.path.abspath(__file__)))

PyInstaller.__main__.run([
    'excel_merger.py',
    '--onefile',
    '--windowed',
    '--name=Excel合并工具',
    '--clean',
    '--noconfirm',
    '--hidden-import=pandas._libs.tslibs.base',
    '--hidden-import=pandas._libs.tslibs.timedeltas',
    '--hidden-import=pandas._libs.tslibs.timestamps',
    '--hidden-import=pandas._libs.tslibs.timezones',
    '--hidden-import=pandas._libs.tslibs.conversion',
    '--hidden-import=pandas._libs.tslibs.fields',
    '--hidden-import=pandas._libs.tslibs.offsets',
    '--hidden-import=pandas._libs.tslibs.parsing',
    '--hidden-import=pandas._libs.tslibs.period',
    '--hidden-import=pandas._libs.tslibs.strptime',
    '--hidden-import=pandas._libs.tslibs.vectorized',
    '--hidden-import=pandas._libs.tslibs.np_datetime',
    '--hidden-import=pandas._libs.tslibs.nattype',
    '--hidden-import=pandas._libs.window.aggregations',
    '--hidden-import=pandas._libs.window.indexers',
    '--hidden-import=pandas._libs.properties',
    '--hidden-import=pandas._libs.reshape',
    '--hidden-import=pandas._libs.algos',
    '--hidden-import=pandas._libs.groupby',
    '--hidden-import=pandas._libs.indexing',
    '--hidden-import=pandas._libs.index',
    '--hidden-import=pandas._libs.internals',
    '--hidden-import=pandas._libs.join',
    '--hidden-import=pandas._libs.lib',
    '--hidden-import=pandas._libs.ops',
    '--hidden-import=pandas._libs.ops_dispatch',
    '--hidden-import=pandas._libs.parsers',
    '--hidden-import=pandas._libs.reduction',
    '--hidden-import=pandas._libs.sparse',
    '--hidden-import=pandas._libs.testing',
    '--hidden-import=pandas._libs.writers',
    '--hidden-import=pandas._libs.arrays',
    '--hidden-import=pandas._libs.hashtable',
    '--hidden-import=pandas._libs.interval',
    '--hidden-import=pandas._libs.json',
    '--hidden-import=pandas._libs.missing',
    '--hidden-import=pandas._libs.hashing',
    '--hidden-import=openpyxl',
    '--hidden-import=openpyxl.styles',
    '--hidden-import=openpyxl.cell',
    '--hidden-import=openpyxl.worksheet',
    '--hidden-import=openpyxl.reader',
    '--hidden-import=openpyxl.writer',
    '--collect-submodules=pandas',
    '--collect-submodules=openpyxl',
])